export const couplePlans = [
  { value: "Cena romántica" },
  { value: "Noche de películas" },
  { value: "Paseo por la playa" },
  { value: "Cita en un café" },
  { value: "Cocinar juntos" },
  { value: "Maratón de series" },
  { value: "Excursión a la naturaleza" },
  { value: "Spa en casa" },
  { value: "Sesión de fotos" },
  { value: "Ver el atardecer" },
  { value: "Escapada de fin de semana" },
  { value: "Escapada nocturna" },
  { value: "Ir al teatro" },
  { value: "Clases de baile" },
  { value: "Tarde de juegos de mesa" },
  { value: "Hacer un picnic" },
  { value: "Día sin tecnología" },
  { value: "Visitar un museo" },
  { value: "Ir al karaoke" },
  { value: "Leer un libro juntos" },
  { value: "Hacer una lista de sueños" },
];
